//! `tests/envelope_validate.rs` — the attestation-envelope binding harness (COMPONENT-SPEC
//! § envelope validation; harness T-RLY-20 / T-RLY-05 / T-RLY-06). No Circle call, no Miden, no
//! network: deterministic unit tests on `validate::envelope`.
//!
//! **The invariant under test.** INV-DEPOSIT-ATTESTATION-RAW-KECCAK (DC-2): the envelope's
//! `messageHash` binds the payload by **raw keccak256 over the FULL payload** — NOT EIP-712, NOT
//! personal-sign, NOT Poseidon2 — and the attestation is a raw 65-byte `r‖s‖v` secp256k1 signature.
//! A binding check that accepted a plausible-but-wrong digest would let the relayer carry a
//! signature over a DIFFERENT message than the one the faucet keccaks and mints on-chain.
//!
//! **Oracle discipline.** The accept path is not judged against the implementation's own keccak: it
//! is judged against the ONE canonical golden artifact (`xusdc_encoding::vectors`, the DC-2 `att`
//! family), whose digests were generated independently by unit-04's `gen_vectors` and are pinned
//! against the on-chain MASM keccak precompile by unit-04's dual tests. So these tests fail if the
//! relayer's off-chain keccak ever diverges from the digest the FAUCET verifies against.
//!
//! **Rejects are exact.** Every rejection asserts the precise `RelayerError` variant (never
//! `is_err()`), and the mismatch variant's `expected` is asserted to be the true raw-keccak digest —
//! so a check that rejected for the wrong reason, or that compared against the wrong digest family,
//! fails.
//!
//! Covered:
//!   * T-RLY-20 `attestation_envelope_raw_keccak` — accept the raw-keccak vector; REJECT the three
//!     negatives computed over the SAME payload (EIP-712 digest, personal-sign prefix, Poseidon2
//!     word); binding is payload-specific.
//!   * T-RLY-05 `message_hash_mismatch_abort`      — every mismatch class aborts with the exact
//!     variant: per-byte digest corruption, tampered/truncated/extended payload, bad length, bad hex.
//!   * T-RLY-06 `attestation_length_reject`        — attestation ≠ 65B → `BadAttestationLength`;
//!     65B accepted shape-only (NO off-chain ECDSA verification — that is on-chain, faucet-owned).

mod fixtures;

use std::error::Error;

use assert_matches::assert_matches;
use hex::FromHexError;
use rstest::rstest;

use fixtures::{
    canonical_payload, eip712_digest, hex_of, keccak256, personal_sign_digest,
    poseidon2_word_digest, recover_pubkey, test_vector, verify_attestation, with_0x,
    PartnerAttester, FOREIGN_KEY_SEED, PARTNER_PUBKEY_HEX, TEST_VECTOR_ATTESTATION_HEX,
    TEST_VECTOR_MESSAGE_HASH_HEX, TEST_VECTOR_PAYLOAD_ID_EMPTY_HOOKDATA,
};
use xreserve_deposit_relayer::error::{HexField, RelayerError};
use xreserve_deposit_relayer::validate::envelope::{
    validate_attestation_envelope, verify_message_hash,
};
use xusdc_encoding::vectors::{load, AttVector};
use xusdc_encoding::xreserve::encoding::pubkey_commitment;

/// The canonical DC-2 attestation vectors — the independent oracle (see the module docs).
fn att_vectors() -> &'static [AttVector] {
    &load().families.att
}

/// Asserts a malformed-hex rejection names the EXACT field AND preserves the originating
/// [`hex::FromHexError`] as a traversable source (G-RUST preserve-error-source) — through BOTH the
/// typed `hex_source()` accessor and the std `Error::source()` chain (`downcast_ref`), so a
/// rejection that flattened or invented its cause fails.
fn assert_malformed_hex(err: &RelayerError, field: HexField, cause: FromHexError) {
    assert_matches!(err, RelayerError::MalformedHex { field: f, .. } => {
        assert_eq!(*f, field, "the rejection must name the exact wire field");
    });
    assert_eq!(
        err.hex_source(),
        Some(&cause),
        "typed hex_source() must be the originating hex::FromHexError"
    );
    let std_source = err.source().and_then(|s| s.downcast_ref::<FromHexError>());
    assert_eq!(
        std_source,
        Some(&cause),
        "std Error::source() chain must traverse to the originating hex::FromHexError"
    );
}

// ================================================================================================
// T-RLY-20 — attestation_envelope_raw_keccak (the INV-DEPOSIT-ATTESTATION-RAW-KECCAK gate)
// ================================================================================================

/// ACCEPT: for every canonical `att` vector, the envelope binds when `messageHash` is the artifact's
/// INDEPENDENTLY generated raw-keccak digest of the full payload. This is the oracle test: it pins
/// the relayer's off-chain keccak to the exact digest the faucet's on-chain keccak precompile
/// verifies against — not to the relayer's own recomputation.
#[test]
fn t_rly_20_accept_canonical_raw_keccak_vectors() {
    for v in att_vectors() {
        let payload = v.payload();
        let digest = v.digest(); // generated by gen_vectors, pinned against the MASM precompile

        let bound = verify_message_hash(&with_0x(&hex_of(&payload)), &with_0x(&hex_of(&digest)))
            .unwrap_or_else(|e| panic!("{}: canonical raw-keccak vector must bind, got {e}", v.id));

        assert_eq!(
            bound, payload,
            "{}: the bound payload must be the exact decoded wire bytes",
            v.id
        );
        // the artifact's digest IS raw keccak over the full payload (belt-and-braces: proves the
        // oracle itself is the raw-keccak family, so the accept above cannot pass for a wrong reason)
        assert_eq!(
            digest,
            keccak256(&payload),
            "{}: the canonical digest must be raw keccak256(full payload)",
            v.id
        );
    }
}

/// ACCEPT: the partner-held test-vector fixture (the reusable one) binds, in both the `0x`-prefixed
/// wire form and the bare form, and with upper-case hex.
#[rstest]
#[case::prefixed(true, false)]
#[case::bare(false, false)]
#[case::uppercase(true, true)]
fn t_rly_20_accept_partner_fixture(#[case] prefixed: bool, #[case] upper: bool) {
    let tv = test_vector();
    let render = |bytes: &[u8]| {
        let h = hex_of(bytes);
        let h = if upper { h.to_uppercase() } else { h };
        if prefixed {
            with_0x(&h)
        } else {
            h
        }
    };

    let bound = verify_message_hash(&render(tv.payload()), &render(&tv.message_hash()))
        .expect("the partner test vector must bind");
    assert_eq!(bound, tv.payload());
}

/// REJECT (the heart of T-RLY-20): the three plausible-but-WRONG digests, each computed over the
/// SAME payload. Each must abort with `MessageHashMismatch`, and the error's `expected` must be the
/// true raw-keccak digest while `actual` is exactly the wrong digest that was presented — so the
/// check is proven to compare against the raw-keccak family and no other.
#[rstest]
#[case::eip712_typed_data(eip712_digest as fn(&[u8]) -> [u8; 32])]
#[case::personal_sign_prefix(personal_sign_digest)]
#[case::poseidon2_word(poseidon2_word_digest)]
fn t_rly_20_reject_non_raw_keccak_digest(#[case] wrong_digest: fn(&[u8]) -> [u8; 32]) {
    let tv = test_vector();
    let payload = tv.payload();
    let wrong = wrong_digest(payload);

    // the comparator must really be a DIFFERENT digest over the same payload (anti-vacuity: a
    // comparator that collided with raw keccak would make this test pass for the wrong reason)
    assert_ne!(
        wrong,
        keccak256(payload),
        "the negative comparator must differ from the raw-keccak digest"
    );

    let err = verify_message_hash(&with_0x(&hex_of(payload)), &with_0x(&hex_of(&wrong)))
        .expect_err("a non-raw-keccak digest must NOT bind the envelope");

    assert_matches!(
        err,
        RelayerError::MessageHashMismatch { expected, actual } => {
            assert_eq!(expected, keccak256(payload), "`expected` must be the raw keccak256 of the full payload");
            assert_eq!(actual, wrong, "`actual` must be the digest that was presented");
        }
    );
}

/// The three negative comparators are pairwise distinct and none equals the raw-keccak digest —
/// they are three genuinely different constructions over one payload, not the same bytes relabelled.
#[test]
fn t_rly_20_negative_comparators_are_distinct_constructions() {
    let payload = canonical_payload(TEST_VECTOR_PAYLOAD_ID_EMPTY_HOOKDATA);
    let raw = keccak256(&payload);
    let digests = [
        ("raw-keccak", raw),
        ("eip712", eip712_digest(&payload)),
        ("personal-sign", personal_sign_digest(&payload)),
        ("poseidon2", poseidon2_word_digest(&payload)),
    ];

    for (i, (name_a, a)) in digests.iter().enumerate() {
        for (name_b, b) in digests.iter().skip(i + 1) {
            assert_ne!(a, b, "{name_a} and {name_b} must be distinct digests");
        }
    }
}

/// The binding is PAYLOAD-SPECIFIC: the raw-keccak digest of payload A does not bind payload B.
/// (Cross-payload swap — a check that merely validated "some 32-byte keccak-shaped hash" would pass.)
#[test]
fn t_rly_20_binding_is_payload_specific() {
    let a = test_vector();
    let b_payload = canonical_payload(TEST_VECTOR_PAYLOAD_ID_EMPTY_HOOKDATA);
    assert_ne!(a.payload(), b_payload.as_slice(), "distinct payloads");

    let err = verify_message_hash(
        &with_0x(&hex_of(&b_payload)),
        &a.message_hash_hex(), // payload A's digest presented for payload B
    )
    .expect_err("payload A's digest must not bind payload B");

    assert_matches!(err, RelayerError::MessageHashMismatch { expected, actual } => {
        assert_eq!(expected, keccak256(&b_payload));
        assert_eq!(actual, a.message_hash());
    });
}

/// The fixture's attester identity is the one the allowlist is keyed by: the commitment is unit-04's
/// `pubkey_commitment` (DC-3) over the 33-byte compressed pubkey, and the pubkey is deterministic
/// (pinned). This is what the later local-node rows seed via `set_attester`.
#[test]
fn t_rly_20_partner_attester_identity_is_deterministic_and_canonically_keyed() {
    let attester = PartnerAttester::new();
    let pk = attester.pubkey();

    assert_eq!(
        hex_of(&pk),
        PARTNER_PUBKEY_HEX,
        "the partner key must be deterministic across runs/machines (seeded RNG)"
    );
    assert_eq!(pk[0] & 0xfe, 0x02, "compressed SEC1 prefix is 0x02 or 0x03");
    assert_eq!(
        attester.commitment(),
        pubkey_commitment(&pk),
        "the allowlist key must be unit-04's owned Poseidon2 commitment (DC-3), never re-derived"
    );
    // a second construction yields the identical key (no hidden RNG state / time dependence)
    assert_eq!(PartnerAttester::new().pubkey(), pk);
}

/// The fixture signs the RAW keccak digest (not a prefixed/typed one): the attestation it produces
/// for an arbitrary payload always binds through `verify_message_hash`, and is a well-formed 65-byte
/// envelope. This is the reusable path R3/R5/R6 build their attestations with.
///
/// NOTE this asserts SHAPE and REPORTED binding only — that the signature actually COVERS the
/// reported digest is proven cryptographically by
/// [`t_rly_20_fixture_signature_cryptographically_covers_the_raw_keccak_digest`]; without that, a
/// fixture could report a correct `message_hash` while having signed something else entirely.
#[test]
fn t_rly_20_fixture_signs_raw_keccak_for_arbitrary_payloads() {
    let attester = PartnerAttester::new();

    for id in [
        fixtures::TEST_VECTOR_PAYLOAD_ID,
        TEST_VECTOR_PAYLOAD_ID_EMPTY_HOOKDATA,
    ] {
        let payload = canonical_payload(id);
        let tv = attester.attest(&payload);

        assert_eq!(
            tv.message_hash(),
            keccak256(&payload),
            "{id}: the fixture must sign the RAW keccak digest"
        );
        assert_eq!(
            verify_message_hash(&tv.payload_hex(), &tv.message_hash_hex()).expect("binds"),
            payload
        );
        let sig = validate_attestation_envelope(&tv.attestation_hex()).expect("65-byte envelope");
        assert_eq!(sig[..32], tv.r(), "r");
        assert_eq!(sig[32..64], tv.s(), "s");
        assert_eq!(sig[64], tv.v(), "v (carried, unused on-chain)");
    }
}

/// THE fixture invariant: the 65-byte `r‖s‖v` CRYPTOGRAPHICALLY VERIFIES against the RAW-KECCAK
/// digest under the partner pubkey — and against NOTHING ELSE.
///
/// Reporting `message_hash = keccak256(payload)` proves nothing on its own: a fixture could report
/// the right digest while having signed a different one, and every shape/binding test would still
/// pass while the "partner vector signs raw keccak" claim silently died. So the signature is checked
/// with a real ECDSA verification (TEST-ONLY — `k256` is a dev-dependency; the production relayer
/// still never verifies a signature off-chain, that is on-chain at D5d), and is then shown NOT to
/// verify against the three wrong digest families or a single-bit-flipped digest.
#[test]
fn t_rly_20_fixture_signature_cryptographically_covers_the_raw_keccak_digest() {
    let attester = PartnerAttester::new();
    let pubkey = attester.pubkey();

    for id in [
        fixtures::TEST_VECTOR_PAYLOAD_ID,
        TEST_VECTOR_PAYLOAD_ID_EMPTY_HOOKDATA,
    ] {
        let payload = canonical_payload(id);
        let tv = attester.attest(&payload);
        let raw = keccak256(&payload);

        // it verifies over the raw-keccak digest of the FULL payload...
        assert!(
            verify_attestation(&pubkey, &raw, &tv.attestation()),
            "{id}: the attestation must verify over keccak256(full payload) under the partner pubkey"
        );

        // ...and over nothing else: not the wrong hash families,
        for (name, wrong) in [
            ("eip712", eip712_digest(&payload)),
            ("personal-sign", personal_sign_digest(&payload)),
            ("poseidon2", poseidon2_word_digest(&payload)),
        ] {
            assert!(
                !verify_attestation(&pubkey, &wrong, &tv.attestation()),
                "{id}: the attestation must NOT verify over the {name} digest"
            );
        }

        // ...and not a digest that differs by a single bit.
        let mut flipped = raw;
        flipped[0] ^= 0x01;
        assert!(
            !verify_attestation(&pubkey, &flipped, &tv.attestation()),
            "{id}: the attestation must NOT verify over a bit-flipped digest"
        );

        // the recovery id (`v`) is the real one: it recovers exactly the partner pubkey from the
        // raw-keccak digest — so `v` cannot be a stray constant, and the signer cannot be another key
        assert_eq!(
            recover_pubkey(&raw, &tv.attestation()),
            Some(pubkey),
            "{id}: r‖s‖v must recover the partner pubkey over the raw-keccak digest"
        );
    }
}

/// The verification oracle used above is itself sound: it accepts the canonical `att` vectors'
/// INDEPENDENTLY generated (pubkey, digest, signature) triples — data this crate did not produce. An
/// oracle that vacuously returned `true` (or `false`) would fail here or in the negatives above.
#[test]
fn t_rly_20_signature_oracle_accepts_canonical_att_vectors() {
    for v in att_vectors() {
        assert!(
            verify_attestation(&v.pubkey(), &v.digest(), &v.sig()),
            "{}: the canonical attestation must verify under its own pubkey + digest",
            v.id
        );
        assert_eq!(
            recover_pubkey(&v.digest(), &v.sig()),
            Some(v.pubkey()),
            "{}: the canonical r‖s‖v must recover its own pubkey",
            v.id
        );
    }
}

/// The reusable test vector is BYTE-PINNED. secp256k1 signing here is deterministic (RFC 6979), so
/// the partner key's signature over the canonical payload is a fixed 65-byte value: an independent
/// golden pin that catches ANY drift in the key, the digest, or the signing convention — including a
/// fixture that started signing a different digest while still reporting the right `message_hash`.
#[test]
fn t_rly_20_test_vector_is_byte_pinned() {
    let tv = test_vector();

    assert_eq!(
        hex_of(&tv.message_hash()),
        TEST_VECTOR_MESSAGE_HASH_HEX,
        "the pinned messageHash of the canonical payload"
    );
    assert_eq!(
        hex_of(&tv.attestation()),
        TEST_VECTOR_ATTESTATION_HEX,
        "the pinned 65-byte r‖s‖v (RFC 6979 deterministic signing)"
    );
    // the pin is a REAL signature over the pinned digest, not just stable bytes
    assert!(verify_attestation(
        &PartnerAttester::new().pubkey(),
        &tv.message_hash(),
        &tv.attestation()
    ));
}

// ================================================================================================
// T-RLY-05 — message_hash_mismatch_abort (every mismatch class, exact variant)
// ================================================================================================

/// A single flipped bit ANYWHERE in the 32-byte digest aborts. Runs all 32 byte positions — a check
/// that compared only a prefix (or, say, 4 felts' worth) of the digest is caught.
#[test]
fn t_rly_05_single_bit_flip_in_any_digest_byte_aborts() {
    let tv = test_vector();
    let truth = tv.message_hash();

    for i in 0..32 {
        let mut corrupted = truth;
        corrupted[i] ^= 0x01;

        let err = verify_message_hash(&tv.payload_hex(), &with_0x(&hex_of(&corrupted)))
            .expect_err(&format!("byte {i}: a corrupted digest must abort"));

        assert_matches!(err, RelayerError::MessageHashMismatch { expected, actual } => {
            assert_eq!(expected, truth, "byte {i}: expected = the true raw-keccak digest");
            assert_eq!(actual, corrupted, "byte {i}: actual = the presented digest");
        });
    }
}

/// The payload is bound too: tampering with the payload while presenting the ORIGINAL `messageHash`
/// aborts (a flipped byte, a truncation, and an appended byte). This is the ASG-12 shape — the hash
/// must cover the full payload, so no payload edit can slip past the binding.
#[rstest]
#[case::flipped_byte_first(0)]
#[case::flipped_byte_middle(120)]
#[case::flipped_byte_last(239)]
fn t_rly_05_tampered_payload_aborts(#[case] index: usize) {
    let tv = test_vector();
    let mut tampered = tv.payload().to_vec();
    tampered[index] ^= 0x01;

    let err = verify_message_hash(&with_0x(&hex_of(&tampered)), &tv.message_hash_hex())
        .expect_err("a tampered payload must not bind the original messageHash");

    assert_matches!(err, RelayerError::MessageHashMismatch { expected, actual } => {
        assert_eq!(expected, keccak256(&tampered));
        assert_eq!(actual, tv.message_hash());
    });
}

#[rstest]
#[case::truncated(-1i32)]
#[case::extended(1i32)]
fn t_rly_05_resized_payload_aborts(#[case] delta: i32) {
    let tv = test_vector();
    let mut resized = tv.payload().to_vec();
    if delta < 0 {
        resized.pop();
    } else {
        resized.push(0xab);
    }

    let err = verify_message_hash(&with_0x(&hex_of(&resized)), &tv.message_hash_hex())
        .expect_err("a resized payload must not bind the original messageHash");
    assert_matches!(err, RelayerError::MessageHashMismatch { .. });
}

/// `messageHash` that is not 32 bytes → `BadMessageHashLength` (NOT a mismatch): a shape error is
/// reported as a shape error, with the actual length carried for ops.
#[rstest]
#[case::empty(0)]
#[case::one_byte(1)]
#[case::truncated_31(31)]
#[case::oversized_33(33)]
#[case::doubled_64(64)]
fn t_rly_05_message_hash_wrong_length(#[case] len: usize) {
    let tv = test_vector();
    let bytes = vec![0xab; len];

    let err = verify_message_hash(&tv.payload_hex(), &with_0x(&hex_of(&bytes)))
        .expect_err("a messageHash that is not 32 bytes must abort");

    assert_matches!(err, RelayerError::BadMessageHashLength { actual } => {
        assert_eq!(actual, len);
    });
}

/// Malformed hex in either wire field → the field-specific `MalformedHex`, naming WHICH field and
/// PRESERVING the originating `hex::FromHexError` as a traversable source (never a panic, never a
/// mismatch reported for a decode failure, never a flattened "bad hex").
#[rstest]
#[case::message_hash_odd_length("0xabc", FromHexError::OddLength)]
#[case::message_hash_non_hex_char(
    "0xzz00000000000000000000000000000000000000000000000000000000000000",
    FromHexError::InvalidHexCharacter { c: 'z', index: 0 }
)]
fn t_rly_05_malformed_message_hash_hex(
    #[case] message_hash_hex: &str,
    #[case] cause: FromHexError,
) {
    let tv = test_vector();
    let err = verify_message_hash(&tv.payload_hex(), message_hash_hex)
        .expect_err("malformed messageHash hex must abort");
    assert_malformed_hex(&err, HexField::MessageHash, cause);
}

#[rstest]
#[case::payload_odd_length("0xabc", FromHexError::OddLength)]
#[case::payload_non_hex_char("0x00zz", FromHexError::InvalidHexCharacter { c: 'z', index: 2 })]
// embedded whitespace is a non-hex character (even digit count, so the parity check does not
// pre-empt it — an odd count reports OddLength first, the case below)
#[case::payload_whitespace("0x00 111", FromHexError::InvalidHexCharacter { c: ' ', index: 2 })]
#[case::payload_whitespace_odd_count("0x00 11", FromHexError::OddLength)]
fn t_rly_05_malformed_payload_hex(#[case] payload_hex: &str, #[case] cause: FromHexError) {
    let tv = test_vector();
    let err = verify_message_hash(payload_hex, &tv.message_hash_hex())
        .expect_err("malformed payload hex must abort");
    assert_malformed_hex(&err, HexField::Payload, cause);
}

/// The payload-hex decode failure is reported BEFORE any hash comparison: a request with BOTH a
/// malformed payload and a malformed messageHash surfaces the payload error (deterministic
/// precedence — the payload is the thing being bound, so it is decoded first).
#[test]
fn t_rly_05_payload_hex_error_takes_precedence() {
    let err = verify_message_hash("0xzz", "0xqq").expect_err("both fields malformed");
    assert_matches!(
        err,
        RelayerError::MalformedHex {
            field: HexField::Payload,
            ..
        }
    );
}

// ================================================================================================
// T-RLY-06 (attestation-length sub-case) — attestation ≠ 65B → BadAttestationLength
// ================================================================================================

/// ACCEPT: exactly 65 bytes, returned byte-for-byte (`r‖s‖v` preserved, `v` carried).
#[test]
fn t_rly_06_accept_65_byte_attestation() {
    for v in att_vectors() {
        let sig = v.sig();
        let got = validate_attestation_envelope(&with_0x(&hex_of(&sig))).unwrap_or_else(|e| {
            panic!(
                "{}: a canonical 65-byte attestation must pass, got {e}",
                v.id
            )
        });
        assert_eq!(
            got, sig,
            "{}: returned bytes must be the exact wire bytes",
            v.id
        );
        assert_eq!(got[64], v.v_byte, "{}: v byte carried", v.id);
    }

    // and the bare (un-prefixed) hex form is accepted too
    let tv = test_vector();
    assert_eq!(
        validate_attestation_envelope(&hex_of(&tv.attestation())).expect("bare hex accepted"),
        tv.attestation()
    );
}

/// REJECT: any length other than 65 → `BadAttestationLength`, carrying the actual length.
/// 64 (the `v`-less form) and 66 are the two dangerous neighbours; 0/1/32 cover the degenerate ones.
#[rstest]
#[case::empty(0)]
#[case::one_byte(1)]
#[case::half(32)]
#[case::missing_v_byte(64)]
#[case::one_too_many(66)]
#[case::doubled(130)]
fn t_rly_06_reject_wrong_length_attestation(#[case] len: usize) {
    let bytes = vec![0x11; len];
    let err = validate_attestation_envelope(&with_0x(&hex_of(&bytes)))
        .expect_err("an attestation that is not 65 bytes must be rejected");

    assert_matches!(err, RelayerError::BadAttestationLength { actual } => {
        assert_eq!(actual, len, "the actual length must be carried");
    });
}

/// REJECT: malformed attestation hex → field-specific `MalformedHex` (not a length error), with the
/// originating `hex::FromHexError` preserved as a traversable source.
#[rstest]
#[case::odd_length("0xabc", FromHexError::OddLength)]
#[case::non_hex_char("0xzz", FromHexError::InvalidHexCharacter { c: 'z', index: 0 })]
fn t_rly_06_reject_malformed_attestation_hex(
    #[case] attestation_hex: &str,
    #[case] cause: FromHexError,
) {
    let err = validate_attestation_envelope(attestation_hex)
        .expect_err("malformed attestation hex must abort");
    assert_malformed_hex(&err, HexField::Attestation, cause);
}

/// The envelope check is SHAPE-ONLY — it must NOT verify the ECDSA signature off-chain.
///
/// This is a deliberate, load-bearing behavioural pin (INV: the relayer is a LIVENESS service; the
/// attestation is verified ON-CHAIN at D5d against the attester allowlist, R-MINT-13/14). A 65-byte
/// attestation that is cryptographic nonsense — all zeros, all 0xff, or a valid signature by a
/// DIFFERENT key — is accepted HERE and rejected on-chain. If someone later "helpfully" adds
/// off-chain signature verification, this test fails and tells them why: the relayer must not be
/// able to withhold a mint that the chain would accept, nor authorize one it would not.
#[rstest]
#[case::all_zeros([0u8; 65])]
#[case::all_ones([0xffu8; 65])]
fn t_rly_06_shape_only_never_verifies_ecdsa_offchain(#[case] bytes: [u8; 65]) {
    let got = validate_attestation_envelope(&with_0x(&hex_of(&bytes)))
        .expect("the envelope check is shape-only: 65 bytes is 65 bytes");
    assert_eq!(got, bytes);
}

/// A signature by a GENUINELY DIFFERENT (non-allowlisted) key passes the envelope check — the
/// attester-allowlist gate is on-chain (D5d, R-MINT-13), not here. The foreign attester is a second
/// key with its own seed, so this really is a different signer (not merely a different message);
/// the assertions below pin that: different pubkey, different commitment, and its signature does NOT
/// verify under the partner pubkey — yet the envelope still accepts it, because shape is all the
/// envelope may judge.
#[test]
fn t_rly_06_foreign_key_signature_passes_shape_check() {
    let partner = PartnerAttester::new();
    let foreign = PartnerAttester::with_seed(FOREIGN_KEY_SEED);

    assert_ne!(
        foreign.pubkey(),
        partner.pubkey(),
        "the foreign attester must be a genuinely different key"
    );
    assert_ne!(
        foreign.commitment(),
        partner.commitment(),
        "a different key has a different allowlist commitment (DC-3)"
    );

    // the SAME payload, signed by the foreign key
    let payload = canonical_payload(fixtures::TEST_VECTOR_PAYLOAD_ID);
    let att = foreign.attest(&payload);

    assert!(
        !verify_attestation(&partner.pubkey(), &att.message_hash(), &att.attestation()),
        "the foreign signature must NOT verify under the partner pubkey"
    );
    assert!(
        verify_attestation(&foreign.pubkey(), &att.message_hash(), &att.attestation()),
        "it is a valid signature — just by the wrong (non-allowlisted) key"
    );

    // ...and the envelope accepts it anyway: authority over WHO signed is on-chain.
    assert_eq!(
        validate_attestation_envelope(&att.attestation_hex()).expect("shape-only"),
        att.attestation()
    );
    assert_eq!(
        verify_message_hash(&att.payload_hex(), &att.message_hash_hex()).expect("binds"),
        payload,
        "the envelope binding is about the payload, not the signer"
    );
}
