//! The error messages the shipped MASM raises, as Rust constants.
//!
//! Generated by `build.rs` from the `const ERR_* = "…"` definitions in `asm/`, so the MASM that
//! raises an error is the only place its message is written. Tests assert against these rather than
//! against copied string literals, which is what makes an assertion track a message change instead
//! of silently passing on a stale one.

include!(concat!(env!("OUT_DIR"), "/xreserve_errors.rs"));
