//! `xreserve` faucet account composition (CMP-A15) — the [`XReserveStablecoinBuilder`].

pub mod builder;

pub use builder::{
    BURN_POLICY_PROC_PATH, DOM_MANAGER_ROLE, DOM_PAUSER_ROLE, DOMAIN_CONFIG_SLOT_LABEL,
    IDENTIFIER_CONFIG_SLOT_LABEL, MIN_BURN_SIZE_SLOT_LABEL, MINT_DENY_GUARD_PROC_PATH,
    REQUIRED_XRESERVE_SLOT_LABELS, SOURCE_DOMAIN_CONFIG_SLOT_LABEL, USDCX_DECIMALS,
    USDCX_TOKEN_SYMBOL, USED_NONCES_SLOT_LABEL, XRESERVE_ATTESTERS_SLOT_LABEL,
    XRESERVE_CONTRACT_HI_SLOT_LABEL, XRESERVE_CONTRACT_LO_SLOT_LABEL,
    XReserveStablecoinBuilder, XReserveStablecoinBuilderError,
};
