//! `POST /v1/prepare-withdrawal` — the REQUEST the partner authors.

use bon::Builder;
use serde::{Deserialize, Serialize};

use crate::circle::wire::{
    present_non_null, DecimalAmount, ForwardingFee, Hex32, HexBytes, SchemaError, Token,
};

/// `POST /v1/prepare-withdrawal` request — the top-level `batches[]` **wrapper**.
///
/// The OpenAPI states no `minItems`/`maxItems` for this one (unlike
/// [`WithdrawRequest`](super::WithdrawRequest)), so none is invented.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct PrepareWithdrawalRequest {
    batches: Vec<PrepareBurnIntentInput>,
}

impl PrepareWithdrawalRequest {
    pub fn new(batches: Vec<PrepareBurnIntentInput>) -> Self {
        Self { batches }
    }

    pub fn batches(&self) -> &[PrepareBurnIntentInput] {
        &self.batches
    }
}

/// One `PrepareBurnIntentInput` — the batch the partner authors.
///
/// Eleven fields, five optional, and several of them same-typed 32-byte hex strings with opposite
/// meanings, so construction goes through the generated builder: `remote_depositor` and
/// `final_destination_recipient` cannot be swapped by position when neither is positional
/// (use-bon-builder). The builder's `build` runs the same `Self::validate` serde does.
///
/// **There is no `source_depositor` field, and that is the point.** `sourceDepositor` is a Gateway
/// `TransferSpec` field Circle assigns server-side; the partner supplies `remoteDepositor` — the
/// Miden initiator, taken from the burn note's `metadata.sender` and encoded through the shared
/// encoding crate's `AccountId↔bytes32` codec (consumed by reference).
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Builder)]
#[serde(
    rename_all = "camelCase",
    deny_unknown_fields,
    try_from = "PrepareBurnIntentInputRaw"
)]
#[builder(finish_fn(vis = "", name = build_unchecked))]
pub struct PrepareBurnIntentInput {
    /// `enum: ["USDC"]` — the only member the schema permits.
    ///
    /// The BUILDER defaults it (there is nothing else to choose). Deserialization does **not**: the
    /// OpenAPI marks `token` required, so a body that omits it is refused rather than completed
    /// for. Manufacturing `USDC` for an absent token happens to guess right today — and would guess
    /// silently and wrongly the day Circle adds a second member, on the field naming the asset
    /// being released.
    #[builder(default)]
    token: Token,

    /// A DECIMAL string (e.g. `"10.00"`), mutually exclusive with [`Self::value_including_fees`].
    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    value_excluding_fees: Option<DecimalAmount>,

    /// Mutually exclusive with [`Self::value_excluding_fees`].
    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    value_including_fees: Option<DecimalAmount>,

    /// `minimum: 1` — Miden's domain ("typically greater than 10000"). MUST differ from
    /// [`Self::final_destination_domain`].
    remote_domain: u32,

    /// The Miden account that initiated the withdrawal (the burn note's `metadata.sender`).
    remote_depositor: Hex32,

    /// `minimum: 0` — the CCTP or remote domain the funds finally land on. MUST differ from
    /// [`Self::remote_domain`].
    final_destination_domain: u32,

    final_destination_recipient: Hex32,

    /// If present, the caller must be this address.
    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    final_destination_caller: Option<Hex32>,

    /// **Randomly generated by Circle if omitted** — which is exactly why a present-but-`null` salt
    /// is refused rather than read as absence: the two mean different things to the caller, and
    /// only one of them is a thing the schema describes.
    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    salt: Option<Hex32>,

    use_circle_forwarding: bool,

    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    forwarding_options: Option<ForwardingOptions>,
}

/// The undecorated shape serde parses into, before `PrepareBurnIntentInput::validate` runs. Its
/// only reason to exist is that `try_from` needs somewhere to land — the field-level patterns are
/// already enforced by the newtypes, so what this adds is the CROSS-field rules.
///
/// Note what is NOT here: a `#[serde(default)]` on `token`. It is required, and it is parsed as
/// such.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct PrepareBurnIntentInputRaw {
    token: Token,
    #[serde(default, deserialize_with = "present_non_null")]
    value_excluding_fees: Option<DecimalAmount>,
    #[serde(default, deserialize_with = "present_non_null")]
    value_including_fees: Option<DecimalAmount>,
    remote_domain: u32,
    remote_depositor: Hex32,
    final_destination_domain: u32,
    final_destination_recipient: Hex32,
    #[serde(default, deserialize_with = "present_non_null")]
    final_destination_caller: Option<Hex32>,
    #[serde(default, deserialize_with = "present_non_null")]
    salt: Option<Hex32>,
    use_circle_forwarding: bool,
    #[serde(default, deserialize_with = "present_non_null")]
    forwarding_options: Option<ForwardingOptions>,
}

impl TryFrom<PrepareBurnIntentInputRaw> for PrepareBurnIntentInput {
    type Error = SchemaError;

    fn try_from(raw: PrepareBurnIntentInputRaw) -> Result<Self, Self::Error> {
        let input = Self {
            token: raw.token,
            value_excluding_fees: raw.value_excluding_fees,
            value_including_fees: raw.value_including_fees,
            remote_domain: raw.remote_domain,
            remote_depositor: raw.remote_depositor,
            final_destination_domain: raw.final_destination_domain,
            final_destination_recipient: raw.final_destination_recipient,
            final_destination_caller: raw.final_destination_caller,
            salt: raw.salt,
            use_circle_forwarding: raw.use_circle_forwarding,
            forwarding_options: raw.forwarding_options,
        };
        input.validate()?;
        Ok(input)
    }
}

impl<S: prepare_burn_intent_input_builder::IsComplete> PrepareBurnIntentInputBuilder<S> {
    /// Builds a validated input.
    ///
    /// # Errors
    /// Every variant `PrepareBurnIntentInput::validate` can return.
    pub fn build(self) -> Result<PrepareBurnIntentInput, SchemaError> {
        let input = self.build_unchecked();
        input.validate()?;
        Ok(input)
    }
}

impl PrepareBurnIntentInput {
    /// The cross-field rules the OpenAPI states in prose. One place, reached from both the builder
    /// and serde — so neither path can be the lenient one.
    ///
    /// # Errors
    /// * [`SchemaError::ValueXor`] — both fee fields set, or neither.
    /// * [`SchemaError::RemoteDomainBelowMinimum`] — `remoteDomain < 1`.
    /// * [`SchemaError::DomainsMustDiffer`] — `remoteDomain == finalDestinationDomain`.
    fn validate(&self) -> Result<(), SchemaError> {
        if self.value_excluding_fees.is_some() == self.value_including_fees.is_some() {
            return Err(SchemaError::ValueXor);
        }
        if self.remote_domain < 1 {
            return Err(SchemaError::RemoteDomainBelowMinimum(self.remote_domain));
        }
        if self.remote_domain == self.final_destination_domain {
            return Err(SchemaError::DomainsMustDiffer(self.remote_domain));
        }

        Ok(())
    }

    pub fn token(&self) -> Token {
        self.token
    }

    pub fn value_excluding_fees(&self) -> Option<&str> {
        self.value_excluding_fees
            .as_ref()
            .map(DecimalAmount::as_str)
    }

    pub fn value_including_fees(&self) -> Option<&str> {
        self.value_including_fees
            .as_ref()
            .map(DecimalAmount::as_str)
    }

    pub fn remote_domain(&self) -> u32 {
        self.remote_domain
    }

    /// The Miden burner. NOT `sourceDepositor` — see the type's own docs.
    pub fn remote_depositor(&self) -> &str {
        self.remote_depositor.as_str()
    }

    pub fn final_destination_domain(&self) -> u32 {
        self.final_destination_domain
    }

    pub fn final_destination_recipient(&self) -> &str {
        self.final_destination_recipient.as_str()
    }

    pub fn final_destination_caller(&self) -> Option<&str> {
        self.final_destination_caller.as_ref().map(Hex32::as_str)
    }

    pub fn salt(&self) -> Option<&str> {
        self.salt.as_ref().map(Hex32::as_str)
    }

    pub fn use_circle_forwarding(&self) -> bool {
        self.use_circle_forwarding
    }

    pub fn forwarding_options(&self) -> Option<&ForwardingOptions> {
        self.forwarding_options.as_ref()
    }
}

/// `ForwardingOptions` — all three fields optional, none of them nullable.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct ForwardingOptions {
    /// "In **addition to** `burnIntent.maxFee`", at most 6 decimals.
    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    max_fee: Option<ForwardingFee>,

    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    hook_data: Option<HexBytes>,

    /// "**Required for CCTP forwarding.**"
    #[serde(
        default,
        deserialize_with = "present_non_null",
        skip_serializing_if = "Option::is_none"
    )]
    uses_fast_finality: Option<bool>,
}

impl ForwardingOptions {
    pub fn new(
        max_fee: Option<ForwardingFee>,
        hook_data: Option<HexBytes>,
        uses_fast_finality: Option<bool>,
    ) -> Self {
        Self {
            max_fee,
            hook_data,
            uses_fast_finality,
        }
    }

    pub fn max_fee(&self) -> Option<&str> {
        self.max_fee.as_ref().map(ForwardingFee::as_str)
    }

    pub fn hook_data(&self) -> Option<&str> {
        self.hook_data.as_ref().map(HexBytes::as_str)
    }

    pub fn uses_fast_finality(&self) -> Option<bool> {
        self.uses_fast_finality
    }
}
