//! P5-01 precompile-execution grounding canary — MockChain gate.
//!
//! Proves the Keccak256 + secp256k1-ECDSA precompiles EXECUTE (not merely assemble/`procref`) under
//! the stock `miden-testing` MockChain host, with NO manual host wiring. Each test drives a `pub proc`
//! that `exec`s a core-lib precompile and asserts the host-handler result with running code:
//!   Q1 keccak `hash_bytes` over a known input == an INDEPENDENT (`sha3`) known-answer digest,
//!   Q2/Q3 ecdsa `verify_prehash` returns 1 for a valid triple and 0 for a structurally-valid-but-
//!         invalid one (wrong key / wrong digest) — the load-bearing accept/reject semantics,
//!   Q3 the `verify` wrapper TRAPS ("ECDSA signature verification failed") on a forged-but-well-formed
//!      triple — D5d's fail-closed reject (R-MINT-14),
//!   Q4 every test runs through `MockChain::build_tx_context(...).execute()` with no custom host,
//!   Q5 the pubkey/digest/signature arrive via the advice provider (`extend_advice_inputs`).
//!
//! Anti-circularity: the ECDSA keypair + signature are generated by the INDEPENDENT `k256` crate (and
//! independently re-verified by `k256` before being fed to MASM); the keccak digest by `sha3`.
//! `miden-crypto` is used only as a serialization format-compat check and for the Poseidon2 PK_COMM
//! parity helper — never to sign the vector under test.

use k256::ecdsa::signature::hazmat::PrehashVerifier;
use k256::ecdsa::{RecoveryId, Signature as K256Signature, SigningKey, VerifyingKey};
use rand::{rngs::StdRng, SeedableRng};
use sha3::{Digest, Keccak256};

use miden_crypto::hash::poseidon2::Poseidon2;
use miden_protocol::vm::AdviceInputs;
use miden_protocol::{Felt, Word};
use miden_standards::code_builder::CodeBuilder;
use miden_testing::{Auth, MockChain};

use xusdc_canary_precompile_execution::{CANARY_MASM, CANARY_PATH};

// CONSTANTS (parity with the MASM)
// ================================================================================================

/// 32-byte keccak input (matches the upstream reference vector `(0..32)`). Hashed by the MASM and,
/// independently, by `sha3`; the passing test is the masm-rust-constant-parity check.
const KECCAK_INPUT: [u8; 32] = [
    0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
    26, 27, 28, 29, 30, 31,
];

/// Single-word message for the `verify` (advice) path; small felts so each splits to `[w, 0]` limbs.
const MSG: [u64; 4] = [11, 22, 33, 44];

// VECTOR GENERATION (independent — k256 + sha3)
// ================================================================================================

/// Packs bytes into u32 little-endian field elements: `f_i = u32::from_le_bytes(bytes[4i..4i+4])`,
/// the precompile encoding convention. Trailing bytes of the final limb are zero-padded.
fn pack_le(bytes: &[u8]) -> Vec<Felt> {
    bytes
        .chunks(4)
        .map(|c| {
            let mut a = [0u8; 4];
            a[..c.len()].copy_from_slice(c);
            Felt::from(u32::from_le_bytes(a))
        })
        .collect()
}

/// Keccak256 of `msg` via the INDEPENDENT `sha3` crate (original Keccak, not NIST SHA3-256).
fn keccak256(msg: &[u8]) -> [u8; 32] {
    let mut h = Keccak256::new();
    h.update(msg);
    h.finalize().into()
}

/// 33-byte compressed SEC1 public key of `sk`.
fn pk33(sk: &SigningKey) -> Vec<u8> {
    sk.verifying_key().to_encoded_point(true).as_bytes().to_vec()
}

/// Produces the miden-compatible 65-byte `r || s || v` signature of `digest` under `sk`, generated
/// entirely by `k256` (`sign_prehash_recoverable`) — no miden signing helper. Mirrors
/// `miden-crypto 0.25.1` `Signature { r, s, v }` / `write_into` (r‖s‖v, v = recovery id).
fn sign65(sk: &SigningKey, digest: &[u8; 32]) -> Vec<u8> {
    let (sig, recid): (K256Signature, RecoveryId) =
        sk.sign_prehash_recoverable(digest).expect("k256 prehash sign");
    let mut out = sig.to_bytes().to_vec(); // 64-byte big-endian r || s
    out.push(recid.to_byte()); // v in {0..3}
    assert_eq!(out.len(), 65, "miden ecdsa signature must serialize to 65 bytes (r||s||v)");
    out
}

/// Independent cross-check: `k256`'s own verifier accepts (`expect_valid=true`) or rejects the
/// (pk, digest, sig) triple. Proves the triple is a genuine secp256k1 signature, independent of the
/// miden precompile verifier under test.
fn k256_independently_verifies(vk: &VerifyingKey, digest: &[u8; 32], sig65: &[u8]) -> bool {
    let sig = K256Signature::from_slice(&sig65[..64]).expect("parse r||s");
    vk.verify_prehash(digest, &sig).is_ok()
}

/// PK_COMM = Poseidon2(pk packed as u32 limbs) — the commitment the `verify` wrapper recomputes and
/// asserts. Computed with miden's Poseidon2 (a parity/hash helper, NOT a signer).
fn pk_commitment(pk_bytes: &[u8]) -> Word {
    Poseidon2::hash_elements(&pack_le(pk_bytes))
}

/// Deterministic independent keypair.
fn keypair(seed: u64) -> SigningKey {
    SigningKey::random(&mut StdRng::seed_from_u64(seed))
}

/// Decomposes the single-word MSG to the 32 bytes the `verify` wrapper keccaks internally, matching
/// `word::store_word_u32s_le`: each felt `w` -> `[w_lo (u32 LE), w_hi (u32 LE)]` = 8 bytes.
fn msg_bytes(msg: [u64; 4]) -> [u8; 32] {
    let mut out = [0u8; 32];
    for (i, w) in msg.iter().enumerate() {
        let lo = (*w & 0xFFFF_FFFF) as u32;
        let hi = (*w >> 32) as u32;
        out[i * 8..i * 8 + 4].copy_from_slice(&lo.to_le_bytes());
        out[i * 8 + 4..i * 8 + 8].copy_from_slice(&hi.to_le_bytes());
    }
    out
}

// MASM LITERAL HELPERS
// ================================================================================================

/// Formats a word's four felts as a MASM `[a,b,c,d]` literal using canonical u64 values.
fn word_lit(w: Word) -> String {
    let e: [Felt; 4] = w.into();
    format!("[{},{},{},{}]", e[0], e[1], e[2], e[3])
}

// HARNESS
// ================================================================================================

/// Compiles the canary component, builds a MockChain account from it (zero storage slots), seeds the
/// advice stack, runs `tx_src` against the stock MockChain host, and returns the execution result.
async fn run(
    tx_src: String,
    advice_stack: Vec<Felt>,
) -> anyhow::Result<miden_protocol::transaction::ExecutedTransaction> {
    let code = CodeBuilder::new().compile_component_code(CANARY_PATH, CANARY_MASM)?;
    let metadata =
        miden_protocol::account::component::AccountComponentMetadata::new("xusdc-canary-precompile");
    let component =
        miden_protocol::account::AccountComponent::new(code.clone(), vec![], metadata)?;

    let mut builder = MockChain::builder();
    let account = builder.add_existing_account_from_components(Auth::IncrNonce, [component])?;
    let mock_chain = builder.build()?;

    let tx_script = CodeBuilder::new()
        .with_dynamically_linked_library(&code)?
        .compile_tx_script(tx_src)?;

    let advice = AdviceInputs::default().with_stack(advice_stack);

    let executed = mock_chain
        .build_tx_context(account.id(), &[], &[])?
        .extend_advice_inputs(advice)
        .tx_script(tx_script)
        .build()?
        .execute()
        .await?;
    Ok(executed)
}

// TESTS
// ================================================================================================

/// Q1 — keccak `hash_bytes` EXECUTES and matches an INDEPENDENT (`sha3`) known-answer digest.
#[tokio::test]
async fn keccak_hash_bytes_known_answer() -> anyhow::Result<()> {
    let input_felts = pack_le(&KECCAK_INPUT);
    let expected = keccak256(&KECCAK_INPUT);
    let limbs: Vec<u32> =
        expected.chunks(4).map(|c| u32::from_le_bytes(c.try_into().unwrap())).collect();

    // Compare each returned digest limb d_i (d_0 on top) against the independent expected limb.
    let mut asserts = String::new();
    for (i, e) in limbs.iter().enumerate() {
        asserts.push_str(&format!(
            "    push.{e} assert_eq.err=\"keccak digest limb {i} mismatch\"\n"
        ));
    }
    let tx_src = format!(
        r#"
use {CANARY_PATH}->canary

begin
    call.canary::keccak_hash_bytes_canary
    # => [DIGEST_U32[8], pad(8)]
{asserts}    exec.::miden::core::sys::truncate_stack
end
"#
    );

    let _ = run(tx_src, input_felts).await?;
    println!("[canary] Q1 keccak256::hash_bytes EXECUTED under MockChain; digest == sha3 known-answer.");
    Ok(())
}

/// Q2/Q3-accept, Q5 — ecdsa `verify_prehash` EXECUTES and returns 1 for a valid independent triple.
#[tokio::test]
async fn ecdsa_verify_prehash_accept() -> anyhow::Result<()> {
    let sk = keypair(42);
    let pk = pk33(&sk);
    let digest = keccak256(b"xusdc-precompile-canary-accept");
    let sig = sign65(&sk, &digest);
    assert!(
        k256_independently_verifies(sk.verifying_key(), &digest, &sig),
        "k256 must independently accept the valid triple"
    );

    let advice = [pack_le(&pk), pack_le(&digest), pack_le(&sig)].concat();
    let tx_src = format!(
        r#"
use {CANARY_PATH}->canary

begin
    call.canary::ecdsa_verify_prehash_canary
    # => [result, pad(15)]
    assert.err="valid triple must verify (result==1)"
    exec.::miden::core::sys::truncate_stack
end
"#
    );

    let _ = run(tx_src, advice).await?;
    println!("[canary] Q2/Q3 ecdsa verify_prehash EXECUTED; valid triple -> result == 1 (accept).");
    Ok(())
}

/// Q3-reject (wrong key) — structurally valid signature by the WRONG key -> result == 0 (no trap).
#[tokio::test]
async fn ecdsa_verify_prehash_reject_wrong_key() -> anyhow::Result<()> {
    let sk_real = keypair(42);
    let sk_attacker = keypair(123);
    let pk = pk33(&sk_real); // present the real key
    let digest = keccak256(b"xusdc-precompile-canary-wrong-key");
    let sig = sign65(&sk_attacker, &digest); // signed by a DIFFERENT key (well-formed)
    assert!(
        !k256_independently_verifies(sk_real.verifying_key(), &digest, &sig),
        "k256 must independently reject the wrong-key triple"
    );

    let advice = [pack_le(&pk), pack_le(&digest), pack_le(&sig)].concat();
    let tx_src = format!(
        r#"
use {CANARY_PATH}->canary

begin
    call.canary::ecdsa_verify_prehash_canary
    # => [result, pad(15)]
    assertz.err="wrong-key triple must reject (result==0)"
    exec.::miden::core::sys::truncate_stack
end
"#
    );

    let _ = run(tx_src, advice).await?;
    println!("[canary] Q3 ecdsa verify_prehash EXECUTED; wrong-key triple -> result == 0 (reject).");
    Ok(())
}

/// Q3-reject (wrong digest) — valid signature over a DIFFERENT digest -> result == 0 (no trap).
#[tokio::test]
async fn ecdsa_verify_prehash_reject_wrong_digest() -> anyhow::Result<()> {
    let sk = keypair(42);
    let pk = pk33(&sk);
    let signed_digest = keccak256(b"xusdc-precompile-canary-digest-X");
    let presented_digest = keccak256(b"xusdc-precompile-canary-digest-Y");
    let sig = sign65(&sk, &signed_digest); // valid over X, presented against Y
    assert_ne!(signed_digest, presented_digest);
    assert!(
        !k256_independently_verifies(sk.verifying_key(), &presented_digest, &sig),
        "k256 must independently reject the wrong-digest triple"
    );

    let advice = [pack_le(&pk), pack_le(&presented_digest), pack_le(&sig)].concat();
    let tx_src = format!(
        r#"
use {CANARY_PATH}->canary

begin
    call.canary::ecdsa_verify_prehash_canary
    # => [result, pad(15)]
    assertz.err="wrong-digest triple must reject (result==0)"
    exec.::miden::core::sys::truncate_stack
end
"#
    );

    let _ = run(tx_src, advice).await?;
    println!("[canary] Q3 ecdsa verify_prehash EXECUTED; wrong-digest triple -> result == 0 (reject).");
    Ok(())
}

/// Q2/Q5 (advice path) — the `verify` wrapper EXECUTES and ACCEPTS a valid triple delivered via advice.
#[tokio::test]
async fn ecdsa_verify_accept_via_advice() -> anyhow::Result<()> {
    let sk = keypair(42);
    let pk = pk33(&sk);
    let digest = keccak256(&msg_bytes(MSG)); // the digest `verify` computes internally
    let sig = sign65(&sk, &digest);
    assert!(k256_independently_verifies(sk.verifying_key(), &digest, &sig));

    let pk_comm = word_lit(pk_commitment(&pk));
    let msg = format!("[{},{},{},{}]", MSG[0], MSG[1], MSG[2], MSG[3]);
    // verify reads PK then SIG from advice (no digest — it keccaks the message itself).
    let advice = [pack_le(&pk), pack_le(&sig)].concat();
    let tx_src = format!(
        r#"
use {CANARY_PATH}->canary

begin
    push.{msg}
    push.{pk_comm}
    # => [PK_COMM, MSG, pad(8)]
    call.canary::ecdsa_verify_msg_canary
    # => [pad(16)]  (verify traps on failure; reaching here proves accept)
    exec.::miden::core::sys::truncate_stack
end
"#
    );

    let _ = run(tx_src, advice).await?;
    println!("[canary] Q2/Q5 ecdsa verify (advice path) EXECUTED; valid triple accepted (no trap).");
    Ok(())
}

/// Q3 fail-closed (R-MINT-14) — the `verify` wrapper TRAPS on a structurally-valid forged triple.
#[tokio::test]
async fn ecdsa_verify_trap_on_validly_serialized_invalid() -> anyhow::Result<()> {
    let sk_real = keypair(42);
    let sk_attacker = keypair(123);
    let pk = pk33(&sk_real);
    let digest = keccak256(&msg_bytes(MSG));
    let sig = sign65(&sk_attacker, &digest); // forged by the wrong key, well-formed
    assert!(!k256_independently_verifies(sk_real.verifying_key(), &digest, &sig));

    let pk_comm = word_lit(pk_commitment(&pk));
    let msg = format!("[{},{},{},{}]", MSG[0], MSG[1], MSG[2], MSG[3]);
    let advice = [pack_le(&pk), pack_le(&sig)].concat();
    let tx_src = format!(
        r#"
use {CANARY_PATH}->canary

begin
    push.{msg}
    push.{pk_comm}
    call.canary::ecdsa_verify_msg_canary
    exec.::miden::core::sys::truncate_stack
end
"#
    );

    let err = run(tx_src, advice).await.expect_err("forged triple must TRAP the transaction");
    let msg = format!("{err:#}");
    assert!(
        msg.contains("ECDSA signature verification failed"),
        "expected the verify wrapper's specific trap error, got: {msg}"
    );
    println!("[canary] Q3 ecdsa verify (advice path) EXECUTED; forged triple TRAPPED (fail-closed).");
    Ok(())
}

/// Separate (NOT a boolean-reject proof) — malformed signature bytes -> deserialization/host error,
/// distinct from a boolean `0`. Documents that arbitrary byte tampering is a different failure mode.
#[tokio::test]
async fn ecdsa_verify_prehash_malformed_bytes() -> anyhow::Result<()> {
    let sk = keypair(42);
    let pk = pk33(&sk);
    let digest = keccak256(b"xusdc-precompile-canary-malformed");
    let mut sig = sign65(&sk, &digest);
    sig[64] = 0xFF; // invalid recovery id (v must be <= 3) -> Signature::read_from_bytes fails

    let advice = [pack_le(&pk), pack_le(&digest), pack_le(&sig)].concat();
    let tx_src = format!(
        r#"
use {CANARY_PATH}->canary

begin
    call.canary::ecdsa_verify_prehash_canary
    assertz.err="unreachable: malformed sig should error before returning a boolean"
    exec.::miden::core::sys::truncate_stack
end
"#
    );

    let err = run(tx_src, advice)
        .await
        .expect_err("malformed signature must surface a host/deserialization error, not a boolean 0");
    println!(
        "[canary] malformed-sig case EXECUTED; surfaced a host/deserialization error (NOT a boolean reject): {err:#}"
    );
    Ok(())
}
